directories:
  output: dist_electron
  buildResources: build
appId: io.gxcode.ide
productName: GXCode
copyright: Copyright © 2026 Kyriga
files:
  - filter:
      - main.js
      - preload.js
      - APP/**/*
      - package.json
win:
  target:
    - nsis
  publish:
    - github
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  shortcutName: GXCode
publish:
  provider: github
  owner: Kyriga-CGX
  repo: GXCode
electronVersion: 30.5.1
